export const FETCH_COURSES = 'FETCH_COURSES';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_ADMINS = 'FETCH_ADMINS';
