export const ADD_COURSE_REQUEST = 'ADD_COURSE_REQUEST';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const SORT_COURSES_IN_UI_REQUEST = 'SORT_COURSES_IN_UI_REQUEST';
export const SORT_COURSES_IN_UI_SUCCESS = 'SORT_COURSES_IN_UI_SUCCESS';

export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';

export const FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS';

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_ADMINS = 'FETCH_ADMINS';
